
individual_medal_count_by_country = '''
    CREATE TABLE IF NOT EXISTS {{ params.table_name }} AS (
        WITH medallist(ATHLETES_ID, COUNTRY_ID, COUNTRY_NAME, MEDAL_TYPE) AS (
            SELECT FM.ATHLETES_ID, DA.COUNTRY_ID, COUNTRY_NAME, MEDAL_TYPE
            FROM OLYMPICS_SCHEMA.FACT_MEDALLIST FM
            JOIN OLYMPICS_SCHEMA.DIM_ATHLETES DA ON FM.ATHLETES_ID = DA.ATHLETES_ID
            JOIN OLYMPICS_SCHEMA.DIM_MEDAL DM ON FM.MEDAL_ID = DM.MEDAL_ID
            JOIN OLYMPICS_SCHEMA.DIM_COUNTRY DC ON DA.COUNTRY_ID = DC.COUNTRY_ID
        )
        SELECT COUNTRY_ID, COUNTRY_NAME COUNTRY,
        SUM(CASE WHEN MEDAL_TYPE = 'Gold Medal' THEN 1 ELSE 0 END) GOLD,
        SUM(CASE WHEN MEDAL_TYPE = 'Silver Medal' THEN 1 ELSE 0 END) SILVER,
        SUM(CASE WHEN MEDAL_TYPE = 'Bronze Medal' THEN 1 ELSE 0 END) BRONZE,
        COUNT(*) TOTAL
        FROM medallist
        GROUP BY COUNTRY_ID, COUNTRY_NAME
        ORDER BY TOTAL DESC
    );
'''

team_medal_count_by_country = '''
    CREATE TABLE IF NOT EXISTS {{ params.table_name }} AS (
        WITH medal_team(TEAM_NAME, COUNTRY_ID, COUNTRY_NAME, MEDAL_TYPE) AS(
            SELECT TEAM_NAME, DM.COUNTRY_ID, COUNTRY_NAME, MEDAL_TYPE
            FROM OLYMPICS_SCHEMA.FACT_MEDAL_TEAM FT
            JOIN OLYMPICS_SCHEMA.DIM_TEAM DM ON FT.TEAM_ID = DM.TEAM_ID
            JOIN OLYMPICS_SCHEMA.DIM_MEDAL DME ON FT.MEDAL_ID = DME.MEDAL_ID
            JOIN OLYMPICS_SCHEMA.DIM_COUNTRY DC ON DM.COUNTRY_ID = DC.COUNTRY_ID
        )
        SELECT COUNTRY_ID, COUNTRY_NAME COUNTRY,
        SUM(CASE WHEN MEDAL_TYPE = 'Gold Medal' THEN 1 ELSE 0 END) GOLD,
        SUM(CASE WHEN MEDAL_TYPE = 'Silver Medal' THEN 1 ELSE 0 END) SILVER,
        SUM(CASE WHEN MEDAL_TYPE = 'Bronze Medal' THEN 1 ELSE 0 END) BRONZE,
        COUNT(*) TOTAL
        FROM medal_team
        GROUP BY COUNTRY_ID, COUNTRY_NAME
        ORDER BY TOTAL DESC
    );
'''

total_medal_count_by_country = '''
    CREATE TABLE IF NOT EXISTS {{ params.table_name }} AS (
        SELECT IM.COUNTRY,
        IM.GOLD + TM.GOLD GOLD,
        IM.SILVER + TM.SILVER SILVER,
        IM.BRONZE + TM.BRONZE BRONZE,
        IM.TOTAL + TM.TOTAL TOTAL
        FROM REPORT.INDIVIDUAL_MEDAL_COUNT_BY_COUNTRY IM
        JOIN REPORT.TEAM_MEDAL_COUNT_BY_CONTRY TM ON IM.COUNTRY_ID = TM.COUNTRY_ID
        ORDER BY TOTAL DESC
        LIMIT 10
    );
'''

medallist_attributes = '''
    CREATE TABLE IF NOT EXISTS {{ params.table_name }} AS (
        WITH INDIVIDUAL_MEDAL_ATTRIBUTES(FULL_NAME, AGE, GENDER, MEDAL) AS(
            SELECT FULL_NAME,
            DATEDIFF(YEAR, BIRTH_DATE, '2024-08-11') AGE, GENDER, MEDAL_TYPE
            FROM OLYMPICS_SCHEMA.FACT_MEDALLIST FM
            JOIN OLYMPICS_SCHEMA.DIM_MEDAL DM ON FM.MEDAL_ID = DM.MEDAL_ID
            JOIN OLYMPICS_SCHEMA.DIM_ATHLETES DA ON FM.ATHLETES_ID = DA.ATHLETES_ID
        ),
        TEAM_MEDAL_ATTRIBUTES(FULL_NAME, AGE, GENDER, MEDAL) AS(
            SELECT FULL_NAME,
            DATEDIFF(YEAR, BIRTH_DATE, '2024-08-11') AGE, GENDER, MEDAL_TYPE
            FROM OLYMPICS_SCHEMA.FACT_MEDAL_TEAM FT
            JOIN OLYMPICS_SCHEMA.DIM_MEDAL DM ON FT.MEDAL_ID = DM.MEDAL_ID
            JOIN OLYMPICS_SCHEMA.DIM_TEAM DT ON FT.TEAM_ID = DT.TEAM_ID
            JOIN OLYMPICS_SCHEMA.DIM_ATHLETES_TEAM DAT ON DT.TEAM_ID = DAT.TEAM_ID
            JOIN OLYMPICS_SCHEMA.DIM_ATHLETES DA ON DAT.ATHLETES_ID = DA.ATHLETES_ID
        )
        SELECT * FROM INDIVIDUAL_MEDAL_ATTRIBUTES
        UNION ALL
        SELECT * FROM TEAM_MEDAL_ATTRIBUTES
    );
'''

medallist_age = '''
    CREATE TABLE IF NOT EXISTS {{ params.table_name }} AS (
        SELECT AGE, COUNT(*) TOTAL
        FROM REPORT.MEDALLIST_ATTRIBUTES
        GROUP BY AGE
        ORDER BY AGE
    );
'''

medallist_medal_count = '''
    CREATE TABLE IF NOT EXISTS {{ params.table_name }} AS (
        SELECT FULL_NAME, 
        SUM(CASE WHEN MEDAL_TYPE = 'Gold Medal' THEN 1 ELSE 0 END) GOLD,
        SUM(CASE WHEN MEDAL_TYPE = 'Silver Medal' THEN 1 ELSE 0 END) SILVER,
        SUM(CASE WHEN MEDAL_TYPE = 'Bronze Medal' THEN 1 ELSE 0 END) BRONZE
        FROM REPORT.MEDALLIST_ATTRIBUTES
        GROUP BY FULL_NAME
        ORDER BY TOTAL DESC
    );
'''

medal_count_by_discipline = '''
    CREATE TABLE IF NOT EXISTS {{ params.table_name }} AS (
        WITH INDIVIDUAL_MEDAL_DISCIPLINE(DISCIPLINE) AS(
            SELECT DISCIPLINE_TYPE
            FROM OLYMPICS_SCHEMA.FACT_MEDALLIST FM
            JOIN OLYMPICS_SCHEMA.DIM_DISCIPLINE DD ON FM.DISCIPLINE_ID = DD.DISCIPLINE_ID
        ),
        TEAM_MEDAL_DISCIPLINE(DISCIPLINE) AS(
            SELECT DISCIPLINE_TYPE
            FROM OLYMPICS_SCHEMA.FACT_MEDAL_TEAM FT 
            JOIN OLYMPICS_SCHEMA.DIM_DISCIPLINE DD ON FT.DISCIPLINE_ID = DD.DISCIPLINE_ID
            JOIN OLYMPICS_SCHEMA.DIM_ATHLETES_TEAM DT ON FT.TEAM_ID = DT.TEAM_ID
        ),
        TOTAL_MEDAL_DISCIPLINE(DISCIPLINE) AS(
            SELECT DISCIPLINE FROM INDIVIDUAL_MEDAL_DISCIPLINE
            UNION ALL
            SELECT DISCIPLINE FROM TEAM_MEDAL_DISCIPLINE
        )
        SELECT DISCIPLINE, COUNT(*) TOTAL
        FROM TOTAL_MEDAL_DISCIPLINE 
        GROUP BY DISCIPLINE
        ORDER BY TOTAL DESC
    );

'''